server:
  port: 3000
  servlet:
    context-path: /sooth
spring:
  ## quartz定时任务,采用数据库方式
  quartz:
    job-store-type: jdbc
    initialize-schema: embedded
    #定时任务启动开关，true-开  false-关
    auto-startup: true
    #延迟1秒启动定时任务
    startup-delay: 1s
    #启动时更新己存在的Job
    overwrite-existing-jobs: true
    properties:
      org:
        quartz:
          scheduler:
            instanceName: MyScheduler
            instanceId: AUTO
          jobStore:
            class: org.springframework.scheduling.quartz.LocalDataSourceJobStore
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            isClustered: true
            misfireThreshold: 12000
            clusterCheckinInterval: 15000
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
  datasource:
    master:
      pool-name: MasterDataSource
      jdbc-url: jdbc:mysql://192.168.0.3:3306/sooth?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
      username: root
      password: BMW#Halu@1234%
      driver-class-name: com.mysql.cj.jdbc.Driver
      minimum-idle: 3
      auto-commit: true
      connection-test-query: select 1
      maximum-pool-size: 50
      idle-timeout: 10000
      max-lifetime: 1800000
      connection-timeout: 30000
  #redis 配置
  redis:
    database: 0
    host: 192.168.0.106
    port: 6379
    password: 'halu123456'

