CREATE TABLE "SOOTH"."GEN_BASE_CLASS"
(
    "ID" BIGINT NOT NULL,
    "CLASS_NAME" VARCHAR(200),
    "FIELDS" VARCHAR(255),
    "CREATE_TIME" TIMESTAMP(0),
    "UPDATE_TIME" TIMESTAMP(0),
    "CREATE_BY" VARCHAR(50),
    "UPDATE_BY" VARCHAR(50),
    NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "SOOTH"."GEN_BASE_CLASS" IS '基类管理';
COMMENT ON COLUMN "SOOTH"."GEN_BASE_CLASS"."CLASS_NAME" IS '基类全类名';
COMMENT ON COLUMN "SOOTH"."GEN_BASE_CLASS"."CREATE_BY" IS '创建人';
COMMENT ON COLUMN "SOOTH"."GEN_BASE_CLASS"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "SOOTH"."GEN_BASE_CLASS"."FIELDS" IS '基类字段，多个用英文逗号分隔';
COMMENT ON COLUMN "SOOTH"."GEN_BASE_CLASS"."ID" IS 'id';
COMMENT ON COLUMN "SOOTH"."GEN_BASE_CLASS"."UPDATE_BY" IS '更新人';
COMMENT ON COLUMN "SOOTH"."GEN_BASE_CLASS"."UPDATE_TIME" IS '创建时间';


CREATE TABLE "SOOTH"."GEN_FIELD_TYPE"
(
    "ID" BIGINT NOT NULL,
    "COLUMN_TYPE" VARCHAR(200),
    "ATTR_TYPE" VARCHAR(200),
    NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "SOOTH"."GEN_FIELD_TYPE" IS '字段类型管理';
COMMENT ON COLUMN "SOOTH"."GEN_FIELD_TYPE"."ATTR_TYPE" IS '属性类型';
COMMENT ON COLUMN "SOOTH"."GEN_FIELD_TYPE"."COLUMN_TYPE" IS '字段类型';
COMMENT ON COLUMN "SOOTH"."GEN_FIELD_TYPE"."ID" IS 'id';


CREATE TABLE "SOOTH"."GEN_TABLE"
(
    "ID" BIGINT NOT NULL,
    "TABLE_NAME" VARCHAR(200),
    "CLASS_NAME" VARCHAR(200),
    "TABLE_COMMENT" VARCHAR(200),
    "CREATE_TIME" TIMESTAMP(0),
    "UPDATE_TIME" TIMESTAMP(0),
    "CREATE_BY" VARCHAR(50),
    "UPDATE_BY" VARCHAR(50),
    NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "SOOTH"."GEN_TABLE" IS '代码生成表';
COMMENT ON COLUMN "SOOTH"."GEN_TABLE"."CLASS_NAME" IS '类名';
COMMENT ON COLUMN "SOOTH"."GEN_TABLE"."CREATE_BY" IS '创建人';
COMMENT ON COLUMN "SOOTH"."GEN_TABLE"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "SOOTH"."GEN_TABLE"."ID" IS 'id';
COMMENT ON COLUMN "SOOTH"."GEN_TABLE"."TABLE_COMMENT" IS '说明';
COMMENT ON COLUMN "SOOTH"."GEN_TABLE"."TABLE_NAME" IS '表名';
COMMENT ON COLUMN "SOOTH"."GEN_TABLE"."UPDATE_BY" IS '更新人';
COMMENT ON COLUMN "SOOTH"."GEN_TABLE"."UPDATE_TIME" IS '创建时间';


CREATE TABLE "SOOTH"."GEN_TABLE_FIELD"
(
    "ID" BIGINT NOT NULL,
    "TABLE_ID" BIGINT,
    "COLUMN_NAME" VARCHAR(200),
    "COLUMN_TYPE" VARCHAR(200),
    "COLUMN_COMMENT" VARCHAR(200),
    "ATTR_NAME" VARCHAR(200),
    "ATTR_TYPE" VARCHAR(200),
    "ORDER_NO" INT,
    "PRIMARY_PK" SMALLINT,
    NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "SOOTH"."GEN_TABLE_FIELD" IS '代码生成表字段';
COMMENT ON COLUMN "SOOTH"."GEN_TABLE_FIELD"."ATTR_NAME" IS '属性名';
COMMENT ON COLUMN "SOOTH"."GEN_TABLE_FIELD"."ATTR_TYPE" IS '属性类型';
COMMENT ON COLUMN "SOOTH"."GEN_TABLE_FIELD"."COLUMN_COMMENT" IS '字段说明';
COMMENT ON COLUMN "SOOTH"."GEN_TABLE_FIELD"."COLUMN_NAME" IS '字段名称';
COMMENT ON COLUMN "SOOTH"."GEN_TABLE_FIELD"."COLUMN_TYPE" IS '字段类型';
COMMENT ON COLUMN "SOOTH"."GEN_TABLE_FIELD"."ID" IS 'id';
COMMENT ON COLUMN "SOOTH"."GEN_TABLE_FIELD"."ORDER_NO" IS '排序';
COMMENT ON COLUMN "SOOTH"."GEN_TABLE_FIELD"."PRIMARY_PK" IS '主键 0：否  1：是';
COMMENT ON COLUMN "SOOTH"."GEN_TABLE_FIELD"."TABLE_ID" IS '表ID';


CREATE TABLE "SOOTH"."GEN_TEMPLATE"
(
    "ID" BIGINT NOT NULL,
    "name" VARCHAR(200),
    "CONTENT" CLOB,
    "CREATE_TIME" TIMESTAMP(0),
    "UPDATE_BY" VARCHAR(32),
    "UPDATE_TIME" TIMESTAMP(0),
    "CREATE_BY" VARCHAR(32),
    "GROUP_ID" BIGINT,
    "FILE_NAME" VARCHAR(200),
    NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "SOOTH"."GEN_TEMPLATE" IS '模板配置';
COMMENT ON COLUMN "SOOTH"."GEN_TEMPLATE"."CREATE_BY" IS '创建人登录名称';
COMMENT ON COLUMN "SOOTH"."GEN_TEMPLATE"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "SOOTH"."GEN_TEMPLATE"."FILE_NAME" IS '模板文件名';
COMMENT ON COLUMN "SOOTH"."GEN_TEMPLATE"."GROUP_ID" IS '分组id';
COMMENT ON COLUMN "SOOTH"."GEN_TEMPLATE"."ID" IS 'id';
COMMENT ON COLUMN "SOOTH"."GEN_TEMPLATE"."name" IS '模板名称';
COMMENT ON COLUMN "SOOTH"."GEN_TEMPLATE"."UPDATE_BY" IS '更新人登录名称';
COMMENT ON COLUMN "SOOTH"."GEN_TEMPLATE"."UPDATE_TIME" IS '更新日期';


CREATE TABLE "SOOTH"."GEN_TEMPLATE_GROUP"
(
    "ID" BIGINT NOT NULL,
    "name" VARCHAR(200),
    NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "SOOTH"."GEN_TEMPLATE_GROUP" IS '模板配置组';
COMMENT ON COLUMN "SOOTH"."GEN_TEMPLATE_GROUP"."ID" IS 'id';
COMMENT ON COLUMN "SOOTH"."GEN_TEMPLATE_GROUP"."name" IS '表名';


CREATE TABLE "SOOTH"."PROGRAM_INFO"
(
    "MACHINE_NAME" VARCHAR(100) NOT NULL,
    "PROGRAM_NAME" VARCHAR(100) NOT NULL,
    "DEADLINE" TIMESTAMP(0) NOT NULL,
    "CREAT_TIME" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP(),
    "UPDATE_TIM" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP(),
    NOT CLUSTER PRIMARY KEY("MACHINE_NAME", "PROGRAM_NAME")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "SOOTH"."PROGRAM_INFO" IS '程序运维信息';
COMMENT ON COLUMN "SOOTH"."PROGRAM_INFO"."CREAT_TIME" IS '创建时间';
COMMENT ON COLUMN "SOOTH"."PROGRAM_INFO"."DEADLINE" IS '运维截止时间';
COMMENT ON COLUMN "SOOTH"."PROGRAM_INFO"."MACHINE_NAME" IS '机器名称';
COMMENT ON COLUMN "SOOTH"."PROGRAM_INFO"."PROGRAM_NAME" IS '程序名称';
COMMENT ON COLUMN "SOOTH"."PROGRAM_INFO"."UPDATE_TIM" IS '更新时间';


CREATE TABLE "SOOTH"."PROGRAM_MESSAGES"
(
    "MACHINE_NAME" VARCHAR(255) NOT NULL,
    "PROGRAM_NAME" VARCHAR(255) NOT NULL,
    "MESSAGE" VARCHAR(1024),
    "STATUS" VARCHAR(42) NOT NULL,
    "CREAT_TIME" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP(),
    "UPDATE_TIM" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP()) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "SOOTH"."PROGRAM_MESSAGES" IS '程序消息';
COMMENT ON COLUMN "SOOTH"."PROGRAM_MESSAGES"."CREAT_TIME" IS '创建时间';
COMMENT ON COLUMN "SOOTH"."PROGRAM_MESSAGES"."MACHINE_NAME" IS '机器名称';
COMMENT ON COLUMN "SOOTH"."PROGRAM_MESSAGES"."MESSAGE" IS '消息内容';
COMMENT ON COLUMN "SOOTH"."PROGRAM_MESSAGES"."PROGRAM_NAME" IS '程序名称';
COMMENT ON COLUMN "SOOTH"."PROGRAM_MESSAGES"."STATUS" IS '消息类别';
COMMENT ON COLUMN "SOOTH"."PROGRAM_MESSAGES"."UPDATE_TIM" IS '更新时间';


CREATE TABLE "SOOTH"."SYS_BASE_CLASS"
(
    "ID" BIGINT NOT NULL,
    "CLASS_NAME" VARCHAR(200),
    "FIELDS" VARCHAR(255),
    "CREATE_TIME" TIMESTAMP(0),
    "UPDATE_TIME" TIMESTAMP(0),
    "CREATE_BY" VARCHAR(50),
    "UPDATE_BY" VARCHAR(50),
    NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "SOOTH"."SYS_BASE_CLASS" IS '基类管理';
COMMENT ON COLUMN "SOOTH"."SYS_BASE_CLASS"."CLASS_NAME" IS '基类全类名';
COMMENT ON COLUMN "SOOTH"."SYS_BASE_CLASS"."CREATE_BY" IS '创建人';
COMMENT ON COLUMN "SOOTH"."SYS_BASE_CLASS"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "SOOTH"."SYS_BASE_CLASS"."FIELDS" IS '基类字段，多个用英文逗号分隔';
COMMENT ON COLUMN "SOOTH"."SYS_BASE_CLASS"."ID" IS 'id';
COMMENT ON COLUMN "SOOTH"."SYS_BASE_CLASS"."UPDATE_BY" IS '更新人';
COMMENT ON COLUMN "SOOTH"."SYS_BASE_CLASS"."UPDATE_TIME" IS '创建时间';


CREATE TABLE "SOOTH"."SYS_BUTTON"
(
    "ID" BIGINT NOT NULL,
    "MENU_ID" BIGINT,
    "type" VARCHAR(100),
    NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "SOOTH"."SYS_BUTTON" IS '角色权限表';
COMMENT ON COLUMN "SOOTH"."SYS_BUTTON"."MENU_ID" IS '菜单id';
COMMENT ON COLUMN "SOOTH"."SYS_BUTTON"."type" IS '按钮权限类型';


CREATE TABLE "SOOTH"."SYS_BUTTON_PERMISSION"
(
    "ID" BIGINT NOT NULL,
    "BUTTON_ID" BIGINT,
    "ROLE_ID" BIGINT,
    NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "SOOTH"."SYS_BUTTON_PERMISSION" IS '角色权限表';
COMMENT ON COLUMN "SOOTH"."SYS_BUTTON_PERMISSION"."BUTTON_ID" IS '按钮id';
COMMENT ON COLUMN "SOOTH"."SYS_BUTTON_PERMISSION"."ROLE_ID" IS '角色id';


CREATE TABLE "SOOTH"."SYS_DATA_PERMISSION"
(
    "ID" BIGINT NOT NULL,
    "PERMISSION_CODE" INT,
    "DEPT_IDS" CLOB,
    "ROLE_ID" BIGINT,
    NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "SOOTH"."SYS_DATA_PERMISSION" IS '角色权限表';
COMMENT ON COLUMN "SOOTH"."SYS_DATA_PERMISSION"."DEPT_IDS" IS '指定部门';
COMMENT ON COLUMN "SOOTH"."SYS_DATA_PERMISSION"."PERMISSION_CODE" IS '权限';
COMMENT ON COLUMN "SOOTH"."SYS_DATA_PERMISSION"."ROLE_ID" IS '角色id';


CREATE TABLE "SOOTH"."SYS_DATA_SOURCE"
(
    "ID" BIGINT NOT NULL,
    "name" VARCHAR(100),
    "DESCRIPTION" VARCHAR(255),
    "URL" CLOB,
    "USERNAME" VARCHAR(100),
    "PASSWORD" VARCHAR(100),
    "CREATE_BY" VARCHAR(50),
    "CREATE_TIME" TIMESTAMP(0),
    "UPDATE_BY" VARCHAR(50),
    "UPDATE_TIME" TIMESTAMP(0),
    NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON COLUMN "SOOTH"."SYS_DATA_SOURCE"."CREATE_BY" IS '创建人';
COMMENT ON COLUMN "SOOTH"."SYS_DATA_SOURCE"."CREATE_TIME" IS '创建日期';
COMMENT ON COLUMN "SOOTH"."SYS_DATA_SOURCE"."DESCRIPTION" IS '描述';
COMMENT ON COLUMN "SOOTH"."SYS_DATA_SOURCE"."PASSWORD" IS '密码';
COMMENT ON COLUMN "SOOTH"."SYS_DATA_SOURCE"."UPDATE_BY" IS '更新人';
COMMENT ON COLUMN "SOOTH"."SYS_DATA_SOURCE"."UPDATE_TIME" IS '更新日期';
COMMENT ON COLUMN "SOOTH"."SYS_DATA_SOURCE"."URL" IS '数据源地址';
COMMENT ON COLUMN "SOOTH"."SYS_DATA_SOURCE"."USERNAME" IS '用户名';
COMMENT ON COLUMN "SOOTH"."SYS_DATA_SOURCE"."name" IS '数据源名称';


CREATE TABLE "SOOTH"."SYS_DEPT"
(
    "DEPT_ID" BIGINT NOT NULL,
    "PARENT_ID" BIGINT,
    "DEPT_NAME" VARCHAR(100) NOT NULL,
    "DEPT_CODE" VARCHAR(100),
    "ORDER_NO" NUMBER(22,0),
    "DESCRIPTION" CLOB,
    "STATUS" INT,
    "DEL_FLAG" INT,
    "CREATE_BY" VARCHAR(32),
    "CREATE_TIME" TIMESTAMP(0),
    "UPDATE_BY" VARCHAR(32),
    "UPDATE_TIME" TIMESTAMP(0),
    NOT CLUSTER PRIMARY KEY("DEPT_ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "SOOTH"."SYS_DEPT" IS '组织机构表';
COMMENT ON COLUMN "SOOTH"."SYS_DEPT"."CREATE_BY" IS '创建人';
COMMENT ON COLUMN "SOOTH"."SYS_DEPT"."CREATE_TIME" IS '创建日期';
COMMENT ON COLUMN "SOOTH"."SYS_DEPT"."DEL_FLAG" IS '删除状态（0，正常，1已删除）';
COMMENT ON COLUMN "SOOTH"."SYS_DEPT"."DEPT_CODE" IS '机构/部门编码';
COMMENT ON COLUMN "SOOTH"."SYS_DEPT"."DEPT_ID" IS 'ID';
COMMENT ON COLUMN "SOOTH"."SYS_DEPT"."DEPT_NAME" IS '机构/部门名称';
COMMENT ON COLUMN "SOOTH"."SYS_DEPT"."DESCRIPTION" IS '描述';
COMMENT ON COLUMN "SOOTH"."SYS_DEPT"."ORDER_NO" IS '排序';
COMMENT ON COLUMN "SOOTH"."SYS_DEPT"."PARENT_ID" IS '父机构ID';
COMMENT ON COLUMN "SOOTH"."SYS_DEPT"."STATUS" IS '状态（1启用，0不启用）';
COMMENT ON COLUMN "SOOTH"."SYS_DEPT"."UPDATE_BY" IS '更新人';
COMMENT ON COLUMN "SOOTH"."SYS_DEPT"."UPDATE_TIME" IS '更新日期';


CREATE TABLE "SOOTH"."SYS_DICT"
(
    "ID" BIGINT NOT NULL,
    "name" VARCHAR(100) NOT NULL,
    "CODE" VARCHAR(100) NOT NULL,
    "DESCRIPTION" VARCHAR(255),
    "DEL_FLAG" INT,
    "CREATE_BY" VARCHAR(32),
    "CREATE_TIME" TIMESTAMP(0),
    "UPDATE_BY" VARCHAR(32),
    "UPDATE_TIME" TIMESTAMP(0),
    "TYPE" INT,
    NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON COLUMN "SOOTH"."SYS_DICT"."CODE" IS '字典编码';
COMMENT ON COLUMN "SOOTH"."SYS_DICT"."CREATE_BY" IS '创建人';
COMMENT ON COLUMN "SOOTH"."SYS_DICT"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "SOOTH"."SYS_DICT"."DEL_FLAG" IS '删除状态';
COMMENT ON COLUMN "SOOTH"."SYS_DICT"."DESCRIPTION" IS '描述';
COMMENT ON COLUMN "SOOTH"."SYS_DICT"."TYPE" IS '字典类型0为string,1为number';
COMMENT ON COLUMN "SOOTH"."SYS_DICT"."UPDATE_BY" IS '更新人';
COMMENT ON COLUMN "SOOTH"."SYS_DICT"."UPDATE_TIME" IS '更新时间';
COMMENT ON COLUMN "SOOTH"."SYS_DICT"."name" IS '字典名称';


CREATE TABLE "SOOTH"."SYS_DICT_ITEM"
(
    "ID" BIGINT NOT NULL,
    "DICT_ID" BIGINT,
    "name" VARCHAR(100) NOT NULL,
    "value" VARCHAR(100) NOT NULL,
    "DESCRIPTION" VARCHAR(255),
    "ORDER_NO" NUMBER(22,0),
    "TAG" VARCHAR(200),
    NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON COLUMN "SOOTH"."SYS_DICT_ITEM"."DESCRIPTION" IS '描述';
COMMENT ON COLUMN "SOOTH"."SYS_DICT_ITEM"."DICT_ID" IS '字典id';
COMMENT ON COLUMN "SOOTH"."SYS_DICT_ITEM"."ORDER_NO" IS '排序';
COMMENT ON COLUMN "SOOTH"."SYS_DICT_ITEM"."TAG" IS '颜色标签';
COMMENT ON COLUMN "SOOTH"."SYS_DICT_ITEM"."name" IS '字典项文本';
COMMENT ON COLUMN "SOOTH"."SYS_DICT_ITEM"."value" IS '字典项值';


CREATE TABLE "SOOTH"."SYS_FIELD_TYPE"
(
    "ID" BIGINT NOT NULL,
    "COLUMN_TYPE" VARCHAR(200),
    "ATTR_TYPE" VARCHAR(200),
    NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "SOOTH"."SYS_FIELD_TYPE" IS '字段类型管理';
COMMENT ON COLUMN "SOOTH"."SYS_FIELD_TYPE"."ATTR_TYPE" IS '属性类型';
COMMENT ON COLUMN "SOOTH"."SYS_FIELD_TYPE"."COLUMN_TYPE" IS '字段类型';
COMMENT ON COLUMN "SOOTH"."SYS_FIELD_TYPE"."ID" IS 'id';


CREATE TABLE "SOOTH"."SYS_GEN_FIELD"
(
    "ID" BIGINT NOT NULL,
    "TABLE_ID" BIGINT,
    "COLUMN_NAME" VARCHAR(200),
    "COLUMN_TYPE" VARCHAR(200),
    "COLUMN_COMMENT" VARCHAR(200),
    "ATTR_NAME" VARCHAR(200),
    "ATTR_TYPE" VARCHAR(200),
    "ORDER_NO" INT,
    "PRIMARY_PK" SMALLINT,
    "SHOW_LIST_TYPE" VARCHAR(200),
    "VALID_TYPE" VARCHAR(200),
    "DICT_CODE" VARCHAR(200),
    "SHOW_EDIT_TYPE" VARCHAR(200),
    "CONTROL_TYPE" VARCHAR(200),
    "SEARCH_TYPE" VARCHAR(200),
    NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "SOOTH"."SYS_GEN_FIELD" IS '代码生成表字段';
COMMENT ON COLUMN "SOOTH"."SYS_GEN_FIELD"."ATTR_NAME" IS '属性名';
COMMENT ON COLUMN "SOOTH"."SYS_GEN_FIELD"."ATTR_TYPE" IS '属性类型';
COMMENT ON COLUMN "SOOTH"."SYS_GEN_FIELD"."COLUMN_COMMENT" IS '字段说明';
COMMENT ON COLUMN "SOOTH"."SYS_GEN_FIELD"."COLUMN_NAME" IS '字段名称';
COMMENT ON COLUMN "SOOTH"."SYS_GEN_FIELD"."COLUMN_TYPE" IS '字段类型';
COMMENT ON COLUMN "SOOTH"."SYS_GEN_FIELD"."CONTROL_TYPE" IS '控件类型';
COMMENT ON COLUMN "SOOTH"."SYS_GEN_FIELD"."DICT_CODE" IS '字典';
COMMENT ON COLUMN "SOOTH"."SYS_GEN_FIELD"."ID" IS 'id';
COMMENT ON COLUMN "SOOTH"."SYS_GEN_FIELD"."ORDER_NO" IS '排序';
COMMENT ON COLUMN "SOOTH"."SYS_GEN_FIELD"."PRIMARY_PK" IS '主键 0：否  1：是';
COMMENT ON COLUMN "SOOTH"."SYS_GEN_FIELD"."SEARCH_TYPE" IS '查询方式';
COMMENT ON COLUMN "SOOTH"."SYS_GEN_FIELD"."SHOW_EDIT_TYPE" IS '编辑页显示方式';
COMMENT ON COLUMN "SOOTH"."SYS_GEN_FIELD"."SHOW_LIST_TYPE" IS '列表页显示方式';
COMMENT ON COLUMN "SOOTH"."SYS_GEN_FIELD"."TABLE_ID" IS '表ID';
COMMENT ON COLUMN "SOOTH"."SYS_GEN_FIELD"."VALID_TYPE" IS '校验方式';


CREATE TABLE "SOOTH"."SYS_GEN_GROUP"
(
    "ID" BIGINT NOT NULL,
    "name" VARCHAR(200),
    NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "SOOTH"."SYS_GEN_GROUP" IS '模板配置组';
COMMENT ON COLUMN "SOOTH"."SYS_GEN_GROUP"."ID" IS 'id';
COMMENT ON COLUMN "SOOTH"."SYS_GEN_GROUP"."name" IS '表名';


CREATE TABLE "SOOTH"."SYS_GEN_TABLE"
(
    "ID" BIGINT NOT NULL,
    "TABLE_NAME" VARCHAR(200),
    "CLASS_NAME" VARCHAR(200),
    "TABLE_COMMENT" VARCHAR(200),
    "CREATE_TIME" TIMESTAMP(0),
    "UPDATE_TIME" TIMESTAMP(0),
    "CREATE_BY" VARCHAR(50),
    "UPDATE_BY" VARCHAR(50),
    NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "SOOTH"."SYS_GEN_TABLE" IS '代码生成表';
COMMENT ON COLUMN "SOOTH"."SYS_GEN_TABLE"."CLASS_NAME" IS '类名';
COMMENT ON COLUMN "SOOTH"."SYS_GEN_TABLE"."CREATE_BY" IS '创建人';
COMMENT ON COLUMN "SOOTH"."SYS_GEN_TABLE"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "SOOTH"."SYS_GEN_TABLE"."ID" IS 'id';
COMMENT ON COLUMN "SOOTH"."SYS_GEN_TABLE"."TABLE_COMMENT" IS '说明';
COMMENT ON COLUMN "SOOTH"."SYS_GEN_TABLE"."TABLE_NAME" IS '表名';
COMMENT ON COLUMN "SOOTH"."SYS_GEN_TABLE"."UPDATE_BY" IS '更新人';
COMMENT ON COLUMN "SOOTH"."SYS_GEN_TABLE"."UPDATE_TIME" IS '创建时间';


CREATE TABLE "SOOTH"."SYS_GEN_TEMPLATE"
(
    "ID" BIGINT NOT NULL,
    "name" VARCHAR(200),
    "CONTENT" CLOB,
    "CREATE_TIME" TIMESTAMP(0),
    "UPDATE_BY" VARCHAR(32),
    "UPDATE_TIME" TIMESTAMP(0),
    "CREATE_BY" VARCHAR(32),
    "GROUP_ID" BIGINT,
    "FILE_NAME" VARCHAR(200),
    NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "SOOTH"."SYS_GEN_TEMPLATE" IS '模板配置';
COMMENT ON COLUMN "SOOTH"."SYS_GEN_TEMPLATE"."CREATE_BY" IS '创建人登录名称';
COMMENT ON COLUMN "SOOTH"."SYS_GEN_TEMPLATE"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "SOOTH"."SYS_GEN_TEMPLATE"."FILE_NAME" IS '模板文件名';
COMMENT ON COLUMN "SOOTH"."SYS_GEN_TEMPLATE"."GROUP_ID" IS '分组id';
COMMENT ON COLUMN "SOOTH"."SYS_GEN_TEMPLATE"."ID" IS 'id';
COMMENT ON COLUMN "SOOTH"."SYS_GEN_TEMPLATE"."UPDATE_BY" IS '更新人登录名称';
COMMENT ON COLUMN "SOOTH"."SYS_GEN_TEMPLATE"."UPDATE_TIME" IS '更新日期';
COMMENT ON COLUMN "SOOTH"."SYS_GEN_TEMPLATE"."name" IS '模板名称';


CREATE TABLE "SOOTH"."SYS_INTERFACE_PERMISSION"
(
    "ID" BIGINT NOT NULL,
    "URL" VARCHAR(200),
    "ROLE_ID" BIGINT,
    NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "SOOTH"."SYS_INTERFACE_PERMISSION" IS '角色权限表';
COMMENT ON COLUMN "SOOTH"."SYS_INTERFACE_PERMISSION"."ROLE_ID" IS '角色id';
COMMENT ON COLUMN "SOOTH"."SYS_INTERFACE_PERMISSION"."URL" IS '接口url';


CREATE TABLE "SOOTH"."SYS_LOG"
(
    "ID" BIGINT NOT NULL,
    "LOG_TYPE" VARCHAR(100),
    "USERNAME" VARCHAR(100),
    "REALNAME" VARCHAR(100),
    "IP" VARCHAR(100),
    "METHOD" CLOB,
    "REQUEST_URL" VARCHAR(255),
    "REQUEST_PARAM" CLOB,
    "REQUEST_TYPE" VARCHAR(10),
    "COST_TIME" BIGINT,
    "CREATE_TIME" TIMESTAMP(0),
    "USER_AGENT" VARCHAR(255),
    "STATUS" INT,
    "BIZ_MODULE" VARCHAR(255),
    "DESCRIPTION" VARCHAR(255),
    "MESSAGE" VARCHAR(255),
    "EXCEPTION_CLASS" VARCHAR(255),
    "STACK_TRACE" CLOB,
    NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "SOOTH"."SYS_LOG" IS '系统日志表';
COMMENT ON COLUMN "SOOTH"."SYS_LOG"."BIZ_MODULE" IS '业务模块';
COMMENT ON COLUMN "SOOTH"."SYS_LOG"."COST_TIME" IS '耗时';
COMMENT ON COLUMN "SOOTH"."SYS_LOG"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "SOOTH"."SYS_LOG"."DESCRIPTION" IS '操作描述';
COMMENT ON COLUMN "SOOTH"."SYS_LOG"."EXCEPTION_CLASS" IS '异常类';
COMMENT ON COLUMN "SOOTH"."SYS_LOG"."IP" IS 'IP';
COMMENT ON COLUMN "SOOTH"."SYS_LOG"."LOG_TYPE" IS '日志类型';
COMMENT ON COLUMN "SOOTH"."SYS_LOG"."MESSAGE" IS '错误信息';
COMMENT ON COLUMN "SOOTH"."SYS_LOG"."METHOD" IS '请求java方法';
COMMENT ON COLUMN "SOOTH"."SYS_LOG"."REALNAME" IS '操作用户名称';
COMMENT ON COLUMN "SOOTH"."SYS_LOG"."REQUEST_PARAM" IS '请求参数';
COMMENT ON COLUMN "SOOTH"."SYS_LOG"."REQUEST_TYPE" IS '请求类型';
COMMENT ON COLUMN "SOOTH"."SYS_LOG"."REQUEST_URL" IS '请求路径';
COMMENT ON COLUMN "SOOTH"."SYS_LOG"."STACK_TRACE" IS '详尽异常';
COMMENT ON COLUMN "SOOTH"."SYS_LOG"."STATUS" IS '状态';
COMMENT ON COLUMN "SOOTH"."SYS_LOG"."USERNAME" IS '操作用户账号';
COMMENT ON COLUMN "SOOTH"."SYS_LOG"."USER_AGENT" IS '浏览器';


CREATE TABLE "SOOTH"."SYS_MENU"
(
    "ID" BIGINT NOT NULL,
    "PARENT_ID" BIGINT,
    "name" VARCHAR(255),
    "URL" VARCHAR(255),
    "COMPONENT" VARCHAR(255),
    "REDIRECT" VARCHAR(255),
    "MENU_TYPE" INT,
    "SORT_NO" NUMBER(22,0),
    "FIXED_TAB" SMALLINT,
    "ICON" VARCHAR(255),
    "HIDDEN" INT,
    "HIDE_TAB" INT,
    "DESCRIPTION" VARCHAR(255),
    "CREATE_BY" VARCHAR(255),
    "CREATE_TIME" TIMESTAMP(0),
    "UPDATE_BY" VARCHAR(255),
    "UPDATE_TIME" TIMESTAMP(0),
    "DEL_FLAG" INT,
    "KEEP_ALIVE" SMALLINT,
    "COMPONENT_NAME" VARCHAR(255),
    NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "SOOTH"."SYS_MENU" IS '菜单权限表';
COMMENT ON COLUMN "SOOTH"."SYS_MENU"."COMPONENT" IS '组件';
COMMENT ON COLUMN "SOOTH"."SYS_MENU"."COMPONENT_NAME" IS '组件名称';
COMMENT ON COLUMN "SOOTH"."SYS_MENU"."CREATE_BY" IS '创建人';
COMMENT ON COLUMN "SOOTH"."SYS_MENU"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "SOOTH"."SYS_MENU"."DEL_FLAG" IS '删除状态 0正常 1已删除';
COMMENT ON COLUMN "SOOTH"."SYS_MENU"."DESCRIPTION" IS '描述';
COMMENT ON COLUMN "SOOTH"."SYS_MENU"."FIXED_TAB" IS '聚合子路由: 1是0否';
COMMENT ON COLUMN "SOOTH"."SYS_MENU"."HIDDEN" IS '是否隐藏路由: 0否,1是';
COMMENT ON COLUMN "SOOTH"."SYS_MENU"."HIDE_TAB" IS '是否隐藏tab: 0否,1是';
COMMENT ON COLUMN "SOOTH"."SYS_MENU"."ICON" IS '菜单图标';
COMMENT ON COLUMN "SOOTH"."SYS_MENU"."ID" IS '主键id';
COMMENT ON COLUMN "SOOTH"."SYS_MENU"."KEEP_ALIVE" IS '缓存路由: 1是0否';
COMMENT ON COLUMN "SOOTH"."SYS_MENU"."MENU_TYPE" IS '菜单类型(0:一级菜单; 1:子菜单:2:按钮权限)';
COMMENT ON COLUMN "SOOTH"."SYS_MENU"."PARENT_ID" IS '父id';
COMMENT ON COLUMN "SOOTH"."SYS_MENU"."REDIRECT" IS '一级菜单跳转地址';
COMMENT ON COLUMN "SOOTH"."SYS_MENU"."SORT_NO" IS '菜单排序';
COMMENT ON COLUMN "SOOTH"."SYS_MENU"."UPDATE_BY" IS '更新人';
COMMENT ON COLUMN "SOOTH"."SYS_MENU"."UPDATE_TIME" IS '更新时间';
COMMENT ON COLUMN "SOOTH"."SYS_MENU"."URL" IS '路径';
COMMENT ON COLUMN "SOOTH"."SYS_MENU"."name" IS '菜单标题';


CREATE TABLE "SOOTH"."SYS_QUARTZ"
(
    "ID" BIGINT NOT NULL,
    "CREATE_BY" VARCHAR(32),
    "CREATE_TIME" TIMESTAMP(0),
    "DEL_FLAG" INT,
    "UPDATE_BY" VARCHAR(32),
    "UPDATE_TIME" TIMESTAMP(0),
    "name" VARCHAR(255),
    "CRON" VARCHAR(255),
    "PARAMETER" VARCHAR(255),
    "DESCRIPTION" VARCHAR(255),
    NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "SOOTH"."SYS_QUARTZ" IS '定时任务';
COMMENT ON COLUMN "SOOTH"."SYS_QUARTZ"."CREATE_BY" IS '创建人';
COMMENT ON COLUMN "SOOTH"."SYS_QUARTZ"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "SOOTH"."SYS_QUARTZ"."CRON" IS 'cron表达式';
COMMENT ON COLUMN "SOOTH"."SYS_QUARTZ"."DEL_FLAG" IS '删除状态';
COMMENT ON COLUMN "SOOTH"."SYS_QUARTZ"."DESCRIPTION" IS '描述';
COMMENT ON COLUMN "SOOTH"."SYS_QUARTZ"."PARAMETER" IS '参数';
COMMENT ON COLUMN "SOOTH"."SYS_QUARTZ"."UPDATE_BY" IS '修改人';
COMMENT ON COLUMN "SOOTH"."SYS_QUARTZ"."UPDATE_TIME" IS '修改时间';
COMMENT ON COLUMN "SOOTH"."SYS_QUARTZ"."name" IS '任务名';


CREATE TABLE "SOOTH"."SYS_QUARTZ_JOB"
(
    "ID" VARCHAR(32) NOT NULL,
    "CREATE_BY" VARCHAR(32),
    "CREATE_TIME" TIMESTAMP(0),
    "DEL_FLAG" INT,
    "UPDATE_BY" VARCHAR(32),
    "UPDATE_TIME" TIMESTAMP(0),
    "JOB_NAME" VARCHAR(255),
    "CRON_EXPRESSION" VARCHAR(255),
    "PARAMETER" VARCHAR(255),
    "DESCRIPTION" VARCHAR(255),
    "STATUS" INT,
    NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON COLUMN "SOOTH"."SYS_QUARTZ_JOB"."CREATE_BY" IS '创建人';
COMMENT ON COLUMN "SOOTH"."SYS_QUARTZ_JOB"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "SOOTH"."SYS_QUARTZ_JOB"."CRON_EXPRESSION" IS 'cron表达式';
COMMENT ON COLUMN "SOOTH"."SYS_QUARTZ_JOB"."DEL_FLAG" IS '删除状态';
COMMENT ON COLUMN "SOOTH"."SYS_QUARTZ_JOB"."DESCRIPTION" IS '描述';
COMMENT ON COLUMN "SOOTH"."SYS_QUARTZ_JOB"."JOB_NAME" IS '任务名';
COMMENT ON COLUMN "SOOTH"."SYS_QUARTZ_JOB"."PARAMETER" IS '参数';
COMMENT ON COLUMN "SOOTH"."SYS_QUARTZ_JOB"."STATUS" IS '状态 0正常 -1停止';
COMMENT ON COLUMN "SOOTH"."SYS_QUARTZ_JOB"."UPDATE_BY" IS '修改人';
COMMENT ON COLUMN "SOOTH"."SYS_QUARTZ_JOB"."UPDATE_TIME" IS '修改时间';


CREATE TABLE "SOOTH"."SYS_ROLE"
(
    "ID" BIGINT NOT NULL,
    "ROLE_NAME" VARCHAR(200),
    "ROLE_CODE" VARCHAR(100) NOT NULL,
    "DEPT_ID" BIGINT,
    "DESCRIPTION" VARCHAR(255),
    "CREATE_BY" VARCHAR(32),
    "CREATE_TIME" TIMESTAMP(0),
    "UPDATE_BY" VARCHAR(32),
    "UPDATE_TIME" TIMESTAMP(0),
    NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "SOOTH"."SYS_ROLE" IS '角色表';
COMMENT ON COLUMN "SOOTH"."SYS_ROLE"."CREATE_BY" IS '创建人';
COMMENT ON COLUMN "SOOTH"."SYS_ROLE"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "SOOTH"."SYS_ROLE"."DEPT_ID" IS '部门id';
COMMENT ON COLUMN "SOOTH"."SYS_ROLE"."DESCRIPTION" IS '描述';
COMMENT ON COLUMN "SOOTH"."SYS_ROLE"."ID" IS '主键id';
COMMENT ON COLUMN "SOOTH"."SYS_ROLE"."ROLE_CODE" IS '角色编码';
COMMENT ON COLUMN "SOOTH"."SYS_ROLE"."ROLE_NAME" IS '角色名称';
COMMENT ON COLUMN "SOOTH"."SYS_ROLE"."UPDATE_BY" IS '更新人';
COMMENT ON COLUMN "SOOTH"."SYS_ROLE"."UPDATE_TIME" IS '更新时间';


CREATE TABLE "SOOTH"."SYS_ROLE_PERMISSION"
(
    "ID" BIGINT NOT NULL,
    "ROLE_ID" BIGINT,
    "PERMISSION_ID" BIGINT,
    NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "SOOTH"."SYS_ROLE_PERMISSION" IS '角色权限表';
COMMENT ON COLUMN "SOOTH"."SYS_ROLE_PERMISSION"."PERMISSION_ID" IS '权限id';
COMMENT ON COLUMN "SOOTH"."SYS_ROLE_PERMISSION"."ROLE_ID" IS '角色id';


CREATE TABLE "SOOTH"."SYS_USER"
(
    "ID" BIGINT NOT NULL,
    "USERNAME" VARCHAR(100),
    "REALNAME" VARCHAR(100),
    "PASSWORD" VARCHAR(255),
    "AVATAR" VARCHAR(255),
    "SEX" SMALLINT,
    "PHONE" VARCHAR(45),
    "DEL_FLAG" SMALLINT,
    "CREATE_BY" VARCHAR(32),
    "CREATE_TIME" TIMESTAMP(0),
    "UPDATE_BY" VARCHAR(32),
    "UPDATE_TIME" TIMESTAMP(0),
    NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "SOOTH"."SYS_USER" IS '用户表';
COMMENT ON COLUMN "SOOTH"."SYS_USER"."AVATAR" IS '头像';
COMMENT ON COLUMN "SOOTH"."SYS_USER"."CREATE_BY" IS '创建人';
COMMENT ON COLUMN "SOOTH"."SYS_USER"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "SOOTH"."SYS_USER"."DEL_FLAG" IS '删除状态(0-正常,1-已删除)';
COMMENT ON COLUMN "SOOTH"."SYS_USER"."ID" IS '主键id';
COMMENT ON COLUMN "SOOTH"."SYS_USER"."PASSWORD" IS '密码';
COMMENT ON COLUMN "SOOTH"."SYS_USER"."PHONE" IS '电话';
COMMENT ON COLUMN "SOOTH"."SYS_USER"."REALNAME" IS '真实姓名';
COMMENT ON COLUMN "SOOTH"."SYS_USER"."SEX" IS '性别';
COMMENT ON COLUMN "SOOTH"."SYS_USER"."UPDATE_BY" IS '更新人';
COMMENT ON COLUMN "SOOTH"."SYS_USER"."UPDATE_TIME" IS '更新时间';
COMMENT ON COLUMN "SOOTH"."SYS_USER"."USERNAME" IS '登录账号';


CREATE TABLE "SOOTH"."SYS_USER_DEPT"
(
    "ID" BIGINT NOT NULL,
    "USER_ID" BIGINT,
    "DEPT_ID" BIGINT,
    NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "SOOTH"."SYS_USER_DEPT" IS '用户部门表';
COMMENT ON COLUMN "SOOTH"."SYS_USER_DEPT"."DEPT_ID" IS '部门id';
COMMENT ON COLUMN "SOOTH"."SYS_USER_DEPT"."ID" IS '主键id';
COMMENT ON COLUMN "SOOTH"."SYS_USER_DEPT"."USER_ID" IS '用户id';


CREATE TABLE "SOOTH"."SYS_USER_ROLE"
(
    "ID" BIGINT NOT NULL,
    "USER_ID" BIGINT,
    "ROLE_ID" BIGINT,
    NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "SOOTH"."SYS_USER_ROLE" IS '用户角色表';
COMMENT ON COLUMN "SOOTH"."SYS_USER_ROLE"."ID" IS '主键id';
COMMENT ON COLUMN "SOOTH"."SYS_USER_ROLE"."ROLE_ID" IS '角色id';
COMMENT ON COLUMN "SOOTH"."SYS_USER_ROLE"."USER_ID" IS '用户id';


insert into "SOOTH"."GEN_BASE_CLASS"("ID", "CLASS_NAME", "FIELDS", "CREATE_TIME", "UPDATE_TIME", "CREATE_BY", "UPDATE_BY")
VALUES(<"ID", BIGINT>, <"CLASS_NAME", VARCHAR(200)>, <"FIELDS", VARCHAR(255)>, <"CREATE_TIME", TIMESTAMP(0)>, <"UPDATE_TIME", TIMESTAMP(0)>, <"CREATE_BY", VARCHAR(50)>, <"UPDATE_BY", VARCHAR(50)>);

insert into "SOOTH"."GEN_FIELD_TYPE"("ID", "COLUMN_TYPE", "ATTR_TYPE")
VALUES(<"ID", BIGINT>, <"COLUMN_TYPE", VARCHAR(200)>, <"ATTR_TYPE", VARCHAR(200)>);

insert into "SOOTH"."GEN_TABLE"("ID", "TABLE_NAME", "CLASS_NAME", "TABLE_COMMENT", "CREATE_TIME", "UPDATE_TIME", "CREATE_BY", "UPDATE_BY")
VALUES(<"ID", BIGINT>, <"TABLE_NAME", VARCHAR(200)>, <"CLASS_NAME", VARCHAR(200)>, <"TABLE_COMMENT", VARCHAR(200)>, <"CREATE_TIME", TIMESTAMP(0)>, <"UPDATE_TIME", TIMESTAMP(0)>, <"CREATE_BY", VARCHAR(50)>, <"UPDATE_BY", VARCHAR(50)>);

insert into "SOOTH"."GEN_TABLE_FIELD"("ID", "TABLE_ID", "COLUMN_NAME", "COLUMN_TYPE", "COLUMN_COMMENT", "ATTR_NAME", "ATTR_TYPE", "ORDER_NO", "PRIMARY_PK")
VALUES(<"ID", BIGINT>, <"TABLE_ID", BIGINT>, <"COLUMN_NAME", VARCHAR(200)>, <"COLUMN_TYPE", VARCHAR(200)>, <"COLUMN_COMMENT", VARCHAR(200)>, <"ATTR_NAME", VARCHAR(200)>, <"ATTR_TYPE", VARCHAR(200)>, <"ORDER_NO", INT>, <"PRIMARY_PK", SMALLINT>);

insert into "SOOTH"."GEN_TEMPLATE"("ID", "NAME", "CONTENT", "CREATE_TIME", "UPDATE_BY", "UPDATE_TIME", "CREATE_BY", "GROUP_ID", "FILE_NAME")
VALUES(<"ID", BIGINT>, <"NAME", VARCHAR(200)>, <"CONTENT", CLOB>, <"CREATE_TIME", TIMESTAMP(0)>, <"UPDATE_BY", VARCHAR(32)>, <"UPDATE_TIME", TIMESTAMP(0)>, <"CREATE_BY", VARCHAR(32)>, <"GROUP_ID", BIGINT>, <"FILE_NAME", VARCHAR(200)>);

insert into "SOOTH"."GEN_TEMPLATE_GROUP"("ID", "NAME")
VALUES(<"ID", BIGINT>, <"NAME", VARCHAR(200)>);

insert into "SOOTH"."PROGRAM_INFO"("MACHINE_NAME", "PROGRAM_NAME", "DEADLINE", "CREAT_TIME", "UPDATE_TIM")
VALUES(<"MACHINE_NAME", VARCHAR(100)>, <"PROGRAM_NAME", VARCHAR(100)>, <"DEADLINE", TIMESTAMP(0)>, <"CREAT_TIME", TIMESTAMP(0)>, <"UPDATE_TIM", TIMESTAMP(0)>);

insert into "SOOTH"."PROGRAM_MESSAGES"("MACHINE_NAME", "PROGRAM_NAME", "MESSAGE", "STATUS", "CREAT_TIME", "UPDATE_TIM")
VALUES(<"MACHINE_NAME", VARCHAR(255)>, <"PROGRAM_NAME", VARCHAR(255)>, <"MESSAGE", VARCHAR(1024)>, <"STATUS", VARCHAR(42)>, <"CREAT_TIME", TIMESTAMP(0)>, <"UPDATE_TIM", TIMESTAMP(0)>);

insert into "SOOTH"."SYS_BASE_CLASS"("ID", "CLASS_NAME", "FIELDS", "CREATE_TIME", "UPDATE_TIME", "CREATE_BY", "UPDATE_BY")
VALUES(<"ID", BIGINT>, <"CLASS_NAME", VARCHAR(200)>, <"FIELDS", VARCHAR(255)>, <"CREATE_TIME", TIMESTAMP(0)>, <"UPDATE_TIME", TIMESTAMP(0)>, <"CREATE_BY", VARCHAR(50)>, <"UPDATE_BY", VARCHAR(50)>);

insert into "SOOTH"."SYS_BUTTON"("ID", "MENU_ID", "type")
VALUES(<"ID", BIGINT>, <"MENU_ID", BIGINT>, <"type", VARCHAR(100)>);

insert into "SOOTH"."SYS_BUTTON_PERMISSION"("ID", "BUTTON_ID", "ROLE_ID")
VALUES(<"ID", BIGINT>, <"BUTTON_ID", BIGINT>, <"ROLE_ID", BIGINT>);

insert into "SOOTH"."SYS_DATA_PERMISSION"("ID", "PERMISSION_CODE", "DEPT_IDS", "ROLE_ID")
VALUES(<"ID", BIGINT>, <"PERMISSION_CODE", INT>, <"DEPT_IDS", CLOB>, <"ROLE_ID", BIGINT>);

insert into "SOOTH"."SYS_DATA_SOURCE"("ID", "name", "DESCRIPTION", "URL", "USERNAME", "PASSWORD", "CREATE_BY", "CREATE_TIME", "UPDATE_BY", "UPDATE_TIME")
VALUES(<"ID", BIGINT>, <"name", VARCHAR(100)>, <"DESCRIPTION", VARCHAR(255)>, <"URL", CLOB>, <"USERNAME", VARCHAR(100)>, <"PASSWORD", VARCHAR(100)>, <"CREATE_BY", VARCHAR(50)>, <"CREATE_TIME", TIMESTAMP(0)>, <"UPDATE_BY", VARCHAR(50)>, <"UPDATE_TIME", TIMESTAMP(0)>);

insert into "SOOTH"."SYS_DEPT"("DEPT_ID", "PARENT_ID", "DEPT_NAME", "DEPT_CODE", "ORDER_NO", "DESCRIPTION", "STATUS", "DEL_FLAG", "CREATE_BY", "CREATE_TIME", "UPDATE_BY", "UPDATE_TIME")
VALUES(<"DEPT_ID", BIGINT>, <"PARENT_ID", BIGINT>, <"DEPT_NAME", VARCHAR(100)>, <"DEPT_CODE", VARCHAR(100)>, <"ORDER_NO", NUMBER(22, 0)>, <"DESCRIPTION", CLOB>, <"STATUS", INT>, <"DEL_FLAG", INT>, <"CREATE_BY", VARCHAR(32)>, <"CREATE_TIME", TIMESTAMP(0)>, <"UPDATE_BY", VARCHAR(32)>, <"UPDATE_TIME", TIMESTAMP(0)>);

insert into "SOOTH"."SYS_DICT"("ID", "name", "CODE", "DESCRIPTION", "DEL_FLAG", "CREATE_BY", "CREATE_TIME", "UPDATE_BY", "UPDATE_TIME", "TYPE")
VALUES(<"ID", BIGINT>, <"name", VARCHAR(100)>, <"CODE", VARCHAR(100)>, <"DESCRIPTION", VARCHAR(255)>, <"DEL_FLAG", INT>, <"CREATE_BY", VARCHAR(32)>, <"CREATE_TIME", TIMESTAMP(0)>, <"UPDATE_BY", VARCHAR(32)>, <"UPDATE_TIME", TIMESTAMP(0)>, <"TYPE", INT>);

insert into "SOOTH"."SYS_DICT_ITEM"("ID", "DICT_ID", "name", "value", "DESCRIPTION", "ORDER_NO", "TAG")
VALUES(<"ID", BIGINT>, <"DICT_ID", BIGINT>, <"name", VARCHAR(100)>, <"value", VARCHAR(100)>, <"DESCRIPTION", VARCHAR(255)>, <"ORDER_NO", NUMBER(22, 0)>, <"TAG", VARCHAR(200)>);

insert into "SOOTH"."SYS_FIELD_TYPE"("ID", "COLUMN_TYPE", "ATTR_TYPE")
VALUES(<"ID", BIGINT>, <"COLUMN_TYPE", VARCHAR(200)>, <"ATTR_TYPE", VARCHAR(200)>);

insert into "SOOTH"."SYS_GEN_FIELD"("ID", "TABLE_ID", "COLUMN_NAME", "COLUMN_TYPE", "COLUMN_COMMENT", "ATTR_NAME", "ATTR_TYPE", "ORDER_NO", "PRIMARY_PK", "SHOW_LIST_TYPE", "VALID_TYPE", "DICT_CODE", "SHOW_EDIT_TYPE", "CONTROL_TYPE", "SEARCH_TYPE")
VALUES(<"ID", BIGINT>, <"TABLE_ID", BIGINT>, <"COLUMN_NAME", VARCHAR(200)>, <"COLUMN_TYPE", VARCHAR(200)>, <"COLUMN_COMMENT", VARCHAR(200)>, <"ATTR_NAME", VARCHAR(200)>, <"ATTR_TYPE", VARCHAR(200)>, <"ORDER_NO", INT>, <"PRIMARY_PK", SMALLINT>, <"SHOW_LIST_TYPE", VARCHAR(200)>, <"VALID_TYPE", VARCHAR(200)>, <"DICT_CODE", VARCHAR(200)>, <"SHOW_EDIT_TYPE", VARCHAR(200)>, <"CONTROL_TYPE", VARCHAR(200)>, <"SEARCH_TYPE", VARCHAR(200)>);

insert into "SOOTH"."SYS_GEN_GROUP"("ID", "name")
VALUES(<"ID", BIGINT>, <"name", VARCHAR(200)>);

insert into "SOOTH"."SYS_GEN_TABLE"("ID", "TABLE_NAME", "CLASS_NAME", "TABLE_COMMENT", "CREATE_TIME", "UPDATE_TIME", "CREATE_BY", "UPDATE_BY")
VALUES(<"ID", BIGINT>, <"TABLE_NAME", VARCHAR(200)>, <"CLASS_NAME", VARCHAR(200)>, <"TABLE_COMMENT", VARCHAR(200)>, <"CREATE_TIME", TIMESTAMP(0)>, <"UPDATE_TIME", TIMESTAMP(0)>, <"CREATE_BY", VARCHAR(50)>, <"UPDATE_BY", VARCHAR(50)>);

insert into "SOOTH"."SYS_GEN_TEMPLATE"("ID", "name", "CONTENT", "CREATE_TIME", "UPDATE_BY", "UPDATE_TIME", "CREATE_BY", "GROUP_ID", "FILE_NAME")
VALUES(<"ID", BIGINT>, <"name", VARCHAR(200)>, <"CONTENT", CLOB>, <"CREATE_TIME", TIMESTAMP(0)>, <"UPDATE_BY", VARCHAR(32)>, <"UPDATE_TIME", TIMESTAMP(0)>, <"CREATE_BY", VARCHAR(32)>, <"GROUP_ID", BIGINT>, <"FILE_NAME", VARCHAR(200)>);

insert into "SOOTH"."SYS_INTERFACE_PERMISSION"("ID", "URL", "ROLE_ID")
VALUES(<"ID", BIGINT>, <"URL", VARCHAR(200)>, <"ROLE_ID", BIGINT>);

insert into "SOOTH"."SYS_LOG"("ID", "LOG_TYPE", "USERNAME", "REALNAME", "IP", "METHOD", "REQUEST_URL", "REQUEST_PARAM", "REQUEST_TYPE", "COST_TIME", "CREATE_TIME", "USER_AGENT", "STATUS", "BIZ_MODULE", "DESCRIPTION", "MESSAGE", "EXCEPTION_CLASS", "STACK_TRACE")
VALUES(<"ID", BIGINT>, <"LOG_TYPE", VARCHAR(100)>, <"USERNAME", VARCHAR(100)>, <"REALNAME", VARCHAR(100)>, <"IP", VARCHAR(100)>, <"METHOD", CLOB>, <"REQUEST_URL", VARCHAR(255)>, <"REQUEST_PARAM", CLOB>, <"REQUEST_TYPE", VARCHAR(10)>, <"COST_TIME", BIGINT>, <"CREATE_TIME", TIMESTAMP(0)>, <"USER_AGENT", VARCHAR(255)>, <"STATUS", INT>, <"BIZ_MODULE", VARCHAR(255)>, <"DESCRIPTION", VARCHAR(255)>, <"MESSAGE", VARCHAR(255)>, <"EXCEPTION_CLASS", VARCHAR(255)>, <"STACK_TRACE", CLOB>);

insert into "SOOTH"."SYS_MENU"("ID", "PARENT_ID", "name", "URL", "COMPONENT", "REDIRECT", "MENU_TYPE", "SORT_NO", "FIXED_TAB", "ICON", "HIDDEN", "HIDE_TAB", "DESCRIPTION", "CREATE_BY", "CREATE_TIME", "UPDATE_BY", "UPDATE_TIME", "DEL_FLAG", "KEEP_ALIVE", "COMPONENT_NAME")
VALUES(<"ID", BIGINT>, <"PARENT_ID", BIGINT>, <"name", VARCHAR(255)>, <"URL", VARCHAR(255)>, <"COMPONENT", VARCHAR(255)>, <"REDIRECT", VARCHAR(255)>, <"MENU_TYPE", INT>, <"SORT_NO", NUMBER(22, 0)>, <"FIXED_TAB", SMALLINT>, <"ICON", VARCHAR(255)>, <"HIDDEN", INT>, <"HIDE_TAB", INT>, <"DESCRIPTION", VARCHAR(255)>, <"CREATE_BY", VARCHAR(255)>, <"CREATE_TIME", TIMESTAMP(0)>, <"UPDATE_BY", VARCHAR(255)>, <"UPDATE_TIME", TIMESTAMP(0)>, <"DEL_FLAG", INT>, <"KEEP_ALIVE", SMALLINT>, <"COMPONENT_NAME", VARCHAR(255)>);

insert into "SOOTH"."SYS_QUARTZ"("ID", "CREATE_BY", "CREATE_TIME", "DEL_FLAG", "UPDATE_BY", "UPDATE_TIME", "name", "CRON", "PARAMETER", "DESCRIPTION")
VALUES(<"ID", BIGINT>, <"CREATE_BY", VARCHAR(32)>, <"CREATE_TIME", TIMESTAMP(0)>, <"DEL_FLAG", INT>, <"UPDATE_BY", VARCHAR(32)>, <"UPDATE_TIME", TIMESTAMP(0)>, <"name", VARCHAR(255)>, <"CRON", VARCHAR(255)>, <"PARAMETER", VARCHAR(255)>, <"DESCRIPTION", VARCHAR(255)>);

insert into "SOOTH"."SYS_QUARTZ_JOB"("ID", "CREATE_BY", "CREATE_TIME", "DEL_FLAG", "UPDATE_BY", "UPDATE_TIME", "JOB_NAME", "CRON_EXPRESSION", "PARAMETER", "DESCRIPTION", "STATUS")
VALUES(<"ID", VARCHAR(32)>, <"CREATE_BY", VARCHAR(32)>, <"CREATE_TIME", TIMESTAMP(0)>, <"DEL_FLAG", INT>, <"UPDATE_BY", VARCHAR(32)>, <"UPDATE_TIME", TIMESTAMP(0)>, <"JOB_NAME", VARCHAR(255)>, <"CRON_EXPRESSION", VARCHAR(255)>, <"PARAMETER", VARCHAR(255)>, <"DESCRIPTION", VARCHAR(255)>, <"STATUS", INT>);

insert into "SOOTH"."SYS_ROLE"("ID", "ROLE_NAME", "ROLE_CODE", "DEPT_ID", "DESCRIPTION", "CREATE_BY", "CREATE_TIME", "UPDATE_BY", "UPDATE_TIME")
VALUES(<"ID", BIGINT>, <"ROLE_NAME", VARCHAR(200)>, <"ROLE_CODE", VARCHAR(100)>, <"DEPT_ID", BIGINT>, <"DESCRIPTION", VARCHAR(255)>, <"CREATE_BY", VARCHAR(32)>, <"CREATE_TIME", TIMESTAMP(0)>, <"UPDATE_BY", VARCHAR(32)>, <"UPDATE_TIME", TIMESTAMP(0)>);

insert into "SOOTH"."SYS_ROLE_PERMISSION"("ID", "ROLE_ID", "PERMISSION_ID")
VALUES(<"ID", BIGINT>, <"ROLE_ID", BIGINT>, <"PERMISSION_ID", BIGINT>);

insert into "SOOTH"."SYS_USER"("ID", "USERNAME", "REALNAME", "PASSWORD", "AVATAR", "SEX", "PHONE", "DEL_FLAG", "CREATE_BY", "CREATE_TIME", "UPDATE_BY", "UPDATE_TIME")
VALUES(<"ID", BIGINT>, <"USERNAME", VARCHAR(100)>, <"REALNAME", VARCHAR(100)>, <"PASSWORD", VARCHAR(255)>, <"AVATAR", VARCHAR(255)>, <"SEX", SMALLINT>, <"PHONE", VARCHAR(45)>, <"DEL_FLAG", SMALLINT>, <"CREATE_BY", VARCHAR(32)>, <"CREATE_TIME", TIMESTAMP(0)>, <"UPDATE_BY", VARCHAR(32)>, <"UPDATE_TIME", TIMESTAMP(0)>);

insert into "SOOTH"."SYS_USER_DEPT"("ID", "USER_ID", "DEPT_ID")
VALUES(<"ID", BIGINT>, <"USER_ID", BIGINT>, <"DEPT_ID", BIGINT>);

insert into "SOOTH"."SYS_USER_ROLE"("ID", "USER_ID", "ROLE_ID")
VALUES(<"ID", BIGINT>, <"USER_ID", BIGINT>, <"ROLE_ID", BIGINT>);

