server:
  port: 3100
  servlet:
    context-path: /sooth
management:
  endpoints:
    web:
      exposure:
        include: metrics,httptrace
spring:
  datasource:
    master:
      pool-name: MasterDataSource
      jdbc-url: jdbc:postgresql://127.0.0.1:5432/sooth
      username: postgres
      password: 123456
      driver-class-name: org.postgresql.Driver
      minimum-idle: 3
      auto-commit: true
      connection-test-query: select 1
      maximum-pool-size: 50
      idle-timeout: 10000
      max-lifetime: 1800000
      connection-timeout: 30000
  #redis 配置
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:

sooth:
  defaultPassword: 123456


dream:
  toSQL: com.moxa.dream.antlr.sql.ToPGSQL
  listeners:
    - com.moxa.dream.drive.listener.DebugListener
