server:
  port: 3000
  servlet:
    context-path: /sooth
management:
  endpoints:
    web:
      exposure:
        include: metrics,httptrace
spring:
  datasource:
    master:
      pool-name: MasterDataSource
      jdbc-url: jdbc:mysql://192.168.0.236:3306/sooth?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
      minimum-idle: 3
      auto-commit: true
      connection-test-query: select 1
      maximum-pool-size: 50
      idle-timeout: 10000
      max-lifetime: 1800000
      connection-timeout: 30000
  #redis 配置
  redis:
    database: 0
    host: 192.168.0.236
    port: 6379

